# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "gerold"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["blog", "certifications"]
# robots = ""

[header]
  layout = "basic" # valid options: basic, hamburger, custom

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/gbusch/gbusch.github.io/blob/master/content"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false
  sharingLinks = ["twitter", "reddit", "linkedin", "email"]
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = true
  showSummary = false
  showTableOfContents = true
  groupByYear = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[author]
  name = "Gerold Busch"
  #image = "img/author.jpg"
  headline = "Data Scientist"
  bio = "Data Scientist"
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/gbusch" },
    { gitlab = "https://gitlab.com/gbusch" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/geroldbusch" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  ]